site_name: VC MIPI® CSI-2 Camera Modules
nav:
    - Introduction: index.md
    - Getting Started: getting_started.md
    - Build SD Card Image: build_sd_card_image.md
    - Setup Developer Kit: setup_developer_kit.md
    - Test Camera: test_camera.md
theme: 
    name: material
    font: 
        text: Roboto
    logo: img/favicon.png

extra_css:
  - stylesheets/extra.css