site_name: VC MIPI® CSI-2 camera modules
nav:
#    - Home: index.md
    - Getting Started: getting_started/index.md
    - Build SD Card Image: getting_started/build_sd_card_image.md
    - Setup Developer Kit: getting_started/setup_developer_kit.md
    - Test your Camera: getting_started/test_camera.md
    - Manual Setup: manual_setup/index.md
theme: 
    name: material
    font: 
        text: Roboto
    logo: img/favicon.png

extra_css:
  - stylesheets/extra.css